data_folder_name = r'c:\dev\code\projects\crime\data'
zip_file_name = '6b8bfec85329ce2986785a5fc37b3704104aaff4.zip'
all_raw_pkl_file_name = 'all_raw.pkl'
FALLS_WITHIN = 'Falls within'
filter_falls_within = 'Thames Valley Police'
raw_url = r'https://maps.googleapis.com/maps/api/staticmap?parameters'